package sal.service.home.models.response;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * @author Nicholas Chow
 *
 * Used in every response.
 *
 * responseCode is mapped to a specified case scenario
 * message is the message generated by the backend to sent to the frontend.
 */
public class ResponseModel {

    @JsonProperty("responseCode")
    private Integer responseCode;
    @JsonProperty("message")
    private String message;

    /**
     *
     * @param responseCode mapped to a specified case scenario
     * @param message message sent to frontend.
     */
    public ResponseModel(Integer responseCode, String message) {
        this.responseCode = responseCode;
        this.message = message;
    }

    public Integer getResponseCode() {
        return responseCode;
    }

    public String getMessage() {
        return message;
    }

    public void setResponseCode(Integer responseCode) {
        this.responseCode = responseCode;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}